#pragma once

#define UPPER_RIGHT_CORNER 191
#define UPPER_LEFT_CORNER 218
#define LOWER_RIGHT_CORNER 217
#define LOWER_LEFT_CORNER 192

#define HORIZONTAL_LINE 196
#define VERTICAL_LINE 179

#define SQUARE_BRACKET_LEFT 91
#define SQUARE_BRACKET_RIGHT 93

#define PLUS_SIGN 43
#define SUBTRACT_SIGN 45
#define MULTIPLY_SIGN 46
#define EQUAL_SIGN 61

#define PRINTING_PADDING_ELEMENT 4
#define PRINTING_PRECISION 2